package others.easy.etwenty;


/**
 * 389 Find The Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

public class FindTheDifference {

    private static char findTheDifference(String s, String t) {
        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();
//        Arrays.sort(sArray);
//        Arrays.sort(tArray);
        int result = 0;

        // Slow
//        for (int i = 0; i < sArray.length; i++) {
//            if (sArray[i] != tArray[i])
//                return tArray[i];
//        }
//        return tArray[tArray.length - 1];

        for (int i = 0; i < sArray.length; i++) {
            result ^= sArray[i];
            result ^= tArray[i];
        }
        result ^= tArray[tArray.length - 1];
        return (char) result;
    }
}
